# Zadanie - pobieranie danych z Eurostat
W tym cwiczeniu skorzystamy z paczki do pobrania danych z Eurostat:

Analizowac bedziemy tabele pokazujaca strukture wydatkoW gopsodarstw domowych w zaleznosci od dochodow
https://ec.europa.eu/eurostat/databrowser/view/hbs_str_t223/default/table?lang=en

Bedziemy musieli zainstalowac nastepujace paczki:

In [1]:
install.packages("eurostat")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘proxy’, ‘Rcpp’, ‘e1071’, ‘plyr’, ‘bibtex’, ‘assertthat’, ‘here’, ‘classInt’, ‘countrycode’, ‘ISOweek’, ‘RefManageR’, ‘regions’

In [2]:
require("eurostat")
require("dplyr")

Loading required package: eurostat

Loading required package: dplyr


Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

##Polecenie 1:
Sprawdz w instrukcji jak dziala funkcja get_eurostat

In [3]:
?get_eurostat

### Polecenie 2:
Wykorzystaj funkcje do sciagniecia tabeli hbs_str_t223

Uwaga: Wybrana tabela jest mala - wystarczy argument z tytulem
W przypadku zapytan o inne dane warto budowac filtr z argumentami.

In [4]:
df <- get_eurostat("hbs_str_t223")
head(df)

Table hbs_str_t223 cached at /tmp/RtmpRVnCNd/eurostat/79e76a2d85c44a49b5abbb807be9c6b2.rds

  freq quantile  coicop unit geo TIME_PERIOD values
1 A    QUINTILE1 CP01   PM   AT  1994-01-01  176.2
2 A    QUINTILE1 CP01   PM   AT  1999-01-01  178.6
3 A    QUINTILE1 CP01   PM   AT  2005-01-01  155.0
4 A    QUINTILE1 CP01   PM   AT  2010-01-01  146.0
5 A    QUINTILE1 CP01   PM   AT  2015-01-01  137.0
6 A    QUINTILE1 CP01   PM   AT  2020-01-01  141.0

## Polecenie 3:
Sposrod tych danych:
1. wybierz te, ktore dotycza pierwszego kwintyla dochodów oraz wylacznie wyniki dla 2015 roku.
2. Wybierz 3 kolumny: geo, coicop oraz values

In [8]:
colnames(df)

[1] "freq"        "quantile"    "coicop"      "unit"        "geo"
[6] "TIME_PERIOD" "values"

In [9]:
dane <- df %>% filter(quantile == "QUINTILE1",
                      TIME_PERIOD == "2015-01-01") %>%
               select(geo, coicop, values)

head(dane)

dim(dane)

  geo coicop values
1 AT  CP01   137
2 BE  CP01   134
3 BG  CP01   352
4 CY  CP01   226
5 CZ  CP01   237
6 DE  CP01   146

[1] 1959    3

## Polecenie 4:
Sposrod tych danych wybierz te, gdzie kolumna coicop ma 4 litery:

In [10]:
dane2 <- dane %>% filter(nchar(coicop)== 4)

head(dane2)
dim (dane2)

  geo coicop values
1 AT  CP01   137
2 BE  CP01   134
3 BG  CP01   352
4 CY  CP01   226
5 CZ  CP01   237
6 DE  CP01   146

[1] 408   3

## Polecenie 5:
Przeksztalc te dane z formy dlugiej do krotkiej.

In [11]:
require(tidyr)
dane_dlugie <- dane2 %>% pivot_wider(names_from = "geo", values_from = "values")

dane_dlugie

Loading required package: tidyr

   coicop AT  BE  BG  CY  CZ  DE  DK  EE  EL  ⋯ PL  PT  RO  RS  SE  SI  SK  TR
1  CP01   137 134 352 226 237 146 123 315 225 ⋯ 237 183 386 362 122 177 227 296
2  CP02    33  29  24  30  27  22  31  32  43 ⋯  21  20  46  40  23  23  28  50
3  CP03    43  32  15  35  38  38  40  33  36 ⋯  31  20  24  18  32  35  28  42
4  CP04   327 410 397 322 335 431 426 276 339 ⋯ 424 391 380 342 384 392 428 327
5  CP05    62  36  27  53  48  32  39  58  29 ⋯  33  33  25  38  39  31  40  57
6  CP06    36  48  79  57  34  27  31  77  65 ⋯  51  77  45  47  28  21  38  20
7  CP07    90  79  17 104  46  73  61  36  55 ⋯  41  84  14  41  89 102  45  83
8  CP08    17  42  32  41  46  38  33  50  36 ⋯  39  37  32  35  35  52  46  29
9  CP09    98  57  20  26  81  82  95  75  25 ⋯  38  26  26  20 150  59  43  17
10 CP10    13   4   0  10   2   6   1   2  13 ⋯   3   6   1   2   0   2   2   5
11 CP11    64  38  12  44  40  35  46  11  87 ⋯  40  62   4  11  26  23  34  42
12 CP12    82  92  25  53  67  70  76  35  47 ⋯  41  63  17  44  64  82  41  30
   UK  XK
1  134 475
2   31  51
3   33  37
4  398 274
5   61  39
6   12  36
7   83  29
8   34  24
9   93   3
10  11   1
11  54   8
12  58  22